<?php
session_start();if(!isset($_SESSION["admin"])){header("Location:index.php");exit;}require"database.php";
if(isset($_GET["delete"])){$id=(int)$_GET["delete"];$conn->query("DELETE FROM students WHERE student_id=$id");header("Location:students.php");exit;}
if($_SERVER["REQUEST_METHOD"]==="POST"){
$s=$conn->prepare("INSERT INTO students(student_number,first_name,middle_name,last_name,birth_date,gender,address,contact_number,email,course,year_level) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
$s->bind_param("sssssssssss",$_POST["student_number"],$_POST["first_name"],$_POST["middle_name"],$_POST["last_name"],$_POST["birth_date"],$_POST["gender"],$_POST["address"],$_POST["contact_number"],$_POST["email"],$_POST["course"],$_POST["year_level"]);$s->execute();header("Location:students.php");exit;}
$q=$conn->real_escape_string($_GET["q"]??"");
$list=$conn->query("SELECT * FROM students WHERE student_number LIKE '%$q%' OR first_name LIKE '%$q%' OR last_name LIKE '%$q%' ORDER BY student_id DESC");
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Students - UCC</title><link rel="stylesheet" href="css/style.css"></head><body><?php include"includes_nav.php";?><main class="container"><h2>Student Management</h2>
<div class="card"><h3>Register Student</h3><form method="post" class="grid"><input name="student_number" placeholder="Student Number" required><input name="first_name" placeholder="First Name" required><input name="middle_name" placeholder="Middle Name"><input name="last_name" placeholder="Last Name" required><input type="date" name="birth_date" required><select name="gender" required><option value="">Gender</option><option>Male</option><option>Female</option><option>Prefer not to say</option></select><input name="address" placeholder="Address"><input name="contact_number" placeholder="Contact Number"><input type="email" name="email" placeholder="Email"><input name="course" placeholder="Course / Program" required><select name="year_level" required><option value="">Year Level</option><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>4th Year</option></select><button class="btn primary">Add Student</button></form></div>
<div class="card"><form class="search"><input name="q" value="<?=htmlspecialchars($_GET["q"]??"")?>" placeholder="Search student"><button class="btn">Search</button></form><table><tr><th>Student No.</th><th>Name</th><th>Course</th><th>Year</th><th>Action</th></tr>
<?php while($r=$list->fetch_assoc()):?><tr><td><?=htmlspecialchars($r["student_number"])?></td><td><?=htmlspecialchars($r["last_name"].", ".$r["first_name"]." ".$r["middle_name"])?></td><td><?=htmlspecialchars($r["course"])?></td><td><?=$r["year_level"]?></td><td><a class="danger" onclick="return confirm('Delete student?')" href="?delete=<?=$r["student_id"]?>">Delete</a></td></tr><?php endwhile;?></table></div></main></body></html>